server {
    listen 80; #Escucha el puerto 80
    location / { #Redirige todas las solicitudes a la aplicación Spring Boot del puerto 5000
        proxy_pass http://localhost:5000;
        proxy_set_header Host $host;
    }
}