[supervisord]
# nodaemon=true significa que corre en primer plano (necesario en Docker)
nodaemon=true 

[program:springboot]
# Arranca la aplicación Spring Boot
command=java -jar /app/app.jar
autostart=true
autorestart=true

[program:nginx]
# Arranca Nginx en primer plano
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true